# Generated by Django 5.1.2 on 2024-10-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('origen', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='bandas/')),
                ('fecha_formacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('lanzamiento', models.DateField()),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='albumes/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_total', models.DurationField(blank=True, null=True)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to='discografia.banda')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('duracion', models.TimeField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='canciones/')),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='discografia.album')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='discografia.banda')),
            ],
        ),
    ]
